export const getRankImage = (total: number): string => {
  if (total < 300) return "/public/rank/G.png";
  if (total < 600) return "/public/rank/G+.png";
  if (total < 900) return "/public/rank/F.png";
  if (total < 1300) return "/public/rank/F+.png";
  if (total < 1800) return "/public/rank/E.png";
  if (total < 2300) return "/public/rank/E+.png";
  if (total < 2900) return "/public/rank/D.png";
  if (total < 3500) return "/public/rank/D+.png";
  if (total < 4900) return "/public/rank/C.png";
  if (total < 6500) return "/public/rank/C+.png";
  if (total < 8200) return "/public/rank/B.png";
  if (total < 10000) return "/public/rank/B+.png";
  if (total < 12100) return "/public/rank/A.png";
  if (total < 14500) return "/public/rank/A+.png";
  if (total < 15900) return "/public/rank/S.png";
  if (total < 17500) return "/public/rank/S+.png";
  if (total < 19200) return "/public/rank/SS.png";
  if (total < 19600) return "/public/rank/SS+.png";
  if (total < 20000) return "/public/rank/UG.png";
  if (total < 20400) return "/public/rank/UG1.png";
  if (total < 20800) return "/public/rank/UG2.png";
  if (total < 21200) return "/public/rank/UG3.png";
  if (total < 21600) return "/public/rank/UG4.png";
  if (total < 22100) return "/public/rank/UG5.png";
  return "/public/rank/UG6.png";
};
