import { SkillDefinition } from "@/lib/calc/total";

export const BLUE_SKILLS: SkillDefinition[] = [
  {
    name: "Triple 7s",
    hasAptitudeTie: false,
    fixedScore: 217,
  },
  {
    name: "Shake It Out",
    hasAptitudeTie: false,
    fixedScore: 217,
  },
  {
    name: "Ignited Spirit STA",
    hasAptitudeTie: false,
    fixedScore: 263,
  },
  {
    name: "Corner Recovery",
    hasAptitudeTie: false,
    fixedScore: 217,
  },
  {
    name: "Straightaway Recovery",
    hasAptitudeTie: false,
    fixedScore: 217,
  },
  {
    name: "Lay Low",
    hasAptitudeTie: false,
    fixedScore: 217,
  },
  {
    name: "Pace Strategy",
    hasAptitudeTie: false,
    fixedScore: 217,
  },
  {
    name: "Calm in a Crowd",
    hasAptitudeTie: false,
    fixedScore: 217,
  },
  {
    name: "Familiar Ground",
    hasAptitudeTie: false,
    fixedScore: 217,
  },

  {
    name: "Be Still",
    hasAptitudeTie: true,
    aptitude: "LATE",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 239,
  },
  {
    name: "Free-Spirited",
    hasAptitudeTie: true,
    aptitude: "LONG",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 195,
  },
  {
    name: "Stamina to Spare",
    hasAptitudeTie: true,
    aptitude: "PACE",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 239,
  },
  {
    name: "Preferred Position",
    hasAptitudeTie: true,
    aptitude: "PACE",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 239,
  },
  {
    name: "Standing By",
    hasAptitudeTie: true,
    aptitude: "END",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 195,
  },
  {
    name: "Wait-and-See",
    hasAptitudeTie: true,
    aptitude: "SPRINT",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 174,
  },
  {
    name: "Watchful Eye",
    hasAptitudeTie: true,
    aptitude: "MILE",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 239,
  },
  {
    name: "Rosy Outlook",
    hasAptitudeTie: true,
    aptitude: "MEDIUM",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 239,
  },
  {
    name: "Deep Breaths",
    hasAptitudeTie: true,
    aptitude: "LONG",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 195,
  },
  {
    name: "Extra Tank",
    hasAptitudeTie: true,
    aptitude: "LONG",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 217,
  },
  {
    name: "Soft Step",
    hasAptitudeTie: true,
    aptitude: "MEDIUM",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 239,
  },
  {
    name: "Passing Pro",
    hasAptitudeTie: true,
    aptitude: "LONG",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 195,
  },
  {
    name: "Moxie",
    hasAptitudeTie: true,
    aptitude: "FRONT",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 174,
  },
  {
    name: "Hydrate",
    hasAptitudeTie: true,
    aptitude: "PACE",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 239,
  },
  {
    name: "A Small Breather",
    hasAptitudeTie: true,
    aptitude: "LATE",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 239,
  },
  {
    name: "After-School Stroll",
    hasAptitudeTie: true,
    aptitude: "END",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 195,
  },
  {
    name: "Levelheaded",
    hasAptitudeTie: true,
    aptitude: "END",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 195,
  },
];
