import { SkillDefinition } from "@/lib/calc/total";

export const GOLD_SKILLS: SkillDefinition[] = [
  {
    name: "Burning Spirit SPD",
    hasAptitudeTie: false,
    fixedScore: 633,
  },
  {
    name: "Burning Spirit STA",
    hasAptitudeTie: false,
    fixedScore: 633,
  },
  {
    name: "Burning Spirit PWR",
    hasAptitudeTie: false,
    fixedScore: 633,
  },
  {
    name: "Burning Spirit GUT",
    hasAptitudeTie: false,
    fixedScore: 633,
  },
  {
    name: "Burning Spirit WIT",
    hasAptitudeTie: false,
    fixedScore: 633,
  },
  {
    name: "Super Lucky Seven",
    hasAptitudeTie: false,
    fixedScore: 334,
  },
  {
    name: "Fall Frenzy",
    hasAptitudeTie: false,
    fixedScore: 461,
  },
  {
    name: "Spring Spectacle",
    hasAptitudeTie: false,
    fixedScore: 461,
  },
  {
    name: "Right-Handed Demon",
    hasAptitudeTie: false,
    fixedScore: 461,
  },
  {
    name: "Yodo Invicta",
    hasAptitudeTie: false,
    fixedScore: 461,
  },
  {
    name: "Firm Course Menace",
    hasAptitudeTie: false,
    fixedScore: 461,
  },
  {
    name: "Swinging Maestro",
    hasAptitudeTie: false,
    fixedScore: 508,
  },
  {
    name: "Breath of Fresh Air",
    hasAptitudeTie: false,
    fixedScore: 508,
  },
  {
    name: "Iron Will",
    hasAptitudeTie: false,
    fixedScore: 508,
  },
  {
    name: "Indomitable",
    hasAptitudeTie: false,
    fixedScore: 508,
  },
  {
    name: "Unruffled",
    hasAptitudeTie: false,
    fixedScore: 508,
  },
  {
    name: "Master of the Sands",
    hasAptitudeTie: false,
    fixedScore: 508,
  },
  {
    name: "Professor of Curvature",
    hasAptitudeTie: false,
    fixedScore: 508,
  },
  {
    name: "Beeline Burst",
    hasAptitudeTie: false,
    fixedScore: 508,
  },
  {
    name: "It's On!",
    hasAptitudeTie: false,
    fixedScore: 508,
  },
  {
    name: "In Body and Mind",
    hasAptitudeTie: false,
    fixedScore: 508,
  },
  {
    name: "Corner Connoisseur",
    hasAptitudeTie: false,
    fixedScore: 508,
  },
  {
    name: "Rushing Gale!",
    hasAptitudeTie: false,
    fixedScore: 508,
  },
  {
    name: "No Stopping Me!",
    hasAptitudeTie: false,
    fixedScore: 394,
  },
  {
    name: "Center Stage",
    hasAptitudeTie: false,
    fixedScore: 334,
  },
  {
    name: "Lane Legerdemain",
    hasAptitudeTie: false,
    fixedScore: 334,
  },
  {
    name: "Concentration",
    hasAptitudeTie: false,
    fixedScore: 394,
  },
  {
    name: "Superstan",
    hasAptitudeTie: false,
    fixedScore: 508,
  },
  {
    name: "Tail Nine",
    hasAptitudeTie: false,
    fixedScore: 508,
  },
  {
    name: "Nothing Ventured",
    hasAptitudeTie: false,
    fixedScore: 334,
  },
  {
    name: "See Ya Later!",
    hasAptitudeTie: false,
    fixedScore: 508,
  },
  {
    name: "Lead the Charge!",
    hasAptitudeTie: false,
    fixedScore: 394,
  },
  {
    name: "Radiant Star",
    hasAptitudeTie: false,
    fixedScore: 633,
  },
  {
    name: "Tantalizing Trick",
    hasAptitudeTie: false,
    fixedScore: 508,
  },

  // changing base on your aptitude

  {
    name: "Runaway",
    hasAptitudeTie: true,
    aptitude: "FRONT",
    aptitudeScores: {
      tier_SA: 407,
      tier_BC: 333,
      tier_DEF: 296,
      tier_G: 259,
    },
    defaultScore: 296,
  },
  {
    name: "Calm and Collected",
    hasAptitudeTie: true,
    aptitude: "PACE",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 559,
  },
  {
    name: "Race Planner",
    hasAptitudeTie: true,
    aptitude: "PACE",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 559,
  },
  {
    name: "Sleeping Lion",
    hasAptitudeTie: true,
    aptitude: "END",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 457,
  },
  {
    name: "Keen Eye",
    hasAptitudeTie: true,
    aptitude: "MILE",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 559,
  },
  {
    name: "Trackblazer",
    hasAptitudeTie: true,
    aptitude: "MEDIUM",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 559,
  },
  {
    name: "Cooldown",
    hasAptitudeTie: true,
    aptitude: "LONG",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 457,
  },
  {
    name: "Adrenaline Rush",
    hasAptitudeTie: true,
    aptitude: "LONG",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 508,
  },
  {
    name: "Miraculous Step",
    hasAptitudeTie: true,
    aptitude: "MEDIUM",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 559,
  },
  {
    name: "Restless",
    hasAptitudeTie: true,
    aptitude: "FRONT",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 406,
  },
  {
    name: "Gourmand",
    hasAptitudeTie: true,
    aptitude: "PACE",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 559,
  },
  {
    name: "Relax",
    hasAptitudeTie: true,
    aptitude: "LATE",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 559,
  },
  {
    name: "Go-Home Specialist",
    hasAptitudeTie: true,
    aptitude: "END",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 457,
  },
  {
    name: "Serenity",
    hasAptitudeTie: true,
    aptitude: "END",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 457,
  },
  {
    name: "Lie in Wait",
    hasAptitudeTie: true,
    aptitude: "LATE",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 559,
  },
  {
    name: "VIP Pass",
    hasAptitudeTie: true,
    aptitude: "LONG",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 457,
  },
  {
    name: "Of Calm Mind",
    hasAptitudeTie: true,
    aptitude: "LONG",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 457,
  },
  {
    name: "Escape Artist",
    hasAptitudeTie: true,
    aptitude: "FRONT",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 406,
  },
  {
    name: "Speed Star",
    hasAptitudeTie: true,
    aptitude: "PACE",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 559,
  },
  {
    name: "Fast & Furious",
    hasAptitudeTie: true,
    aptitude: "LATE",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 559,
  },
  {
    name: "Rising Dragon",
    hasAptitudeTie: true,
    aptitude: "LATE",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 559,
  },
  {
    name: "Sturm und Drang",
    hasAptitudeTie: true,
    aptitude: "END",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 457,
  },
  {
    name: "Blinding Flash",
    hasAptitudeTie: true,
    aptitude: "SPRINT",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 406,
  },
  {
    name: "Mile Maven",
    hasAptitudeTie: true,
    aptitude: "MILE",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 559,
  },
  {
    name: "Killer Tunes",
    hasAptitudeTie: true,
    aptitude: "MEDIUM",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 559,
  },
  {
    name: "Unyielding",
    hasAptitudeTie: true,
    aptitude: "MEDIUM",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 559,
  },
  {
    name: "Innate Experience",
    hasAptitudeTie: true,
    aptitude: "LONG",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 457,
  },
  {
    name: "Staggering Lead",
    hasAptitudeTie: true,
    aptitude: "SPRINT",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 406,
  },
  {
    name: "Changing Gears",
    hasAptitudeTie: true,
    aptitude: "MILE",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 559,
  },
  {
    name: "Big-Sisterly",
    hasAptitudeTie: true,
    aptitude: "MILE",
    aptitudeScores: {
      tier_SA: 367,
      tier_BC: 301,
      tier_DEF: 267,
      tier_G: 234,
    },
    defaultScore: 367,
  },
  {
    name: "Vanguard Spirit",
    hasAptitudeTie: true,
    aptitude: "LONG",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 457,
  },
  {
    name: "Overwhelming Pressure",
    hasAptitudeTie: true,
    aptitude: "LONG",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 457,
  },
  {
    name: "15,000,000 CC",
    hasAptitudeTie: true,
    aptitude: "LATE",
    aptitudeScores: {
      tier_SA: 367,
      tier_BC: 301,
      tier_DEF: 267,
      tier_G: 234,
    },
    defaultScore: 367,
  },
  {
    name: "Taking the Lead",
    hasAptitudeTie: true,
    aptitude: "FRONT",
    aptitudeScores: {
      tier_SA: 367,
      tier_BC: 301,
      tier_DEF: 267,
      tier_G: 234,
    },
    defaultScore: 267,
  },
  {
    name: "Unrestrained",
    hasAptitudeTie: true,
    aptitude: "FRONT",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 406,
  },
  {
    name: "On Your Left!",
    hasAptitudeTie: true,
    aptitude: "LATE",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 559,
  },
  {
    name: "Encroaching Shadow",
    hasAptitudeTie: true,
    aptitude: "END",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 457,
  },
  {
    name: "Turbo Sprint",
    hasAptitudeTie: true,
    aptitude: "SPRINT",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 406,
  },
  {
    name: "Furious Feat",
    hasAptitudeTie: true,
    aptitude: "MILE",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 559,
  },
  {
    name: "Plan X",
    hasAptitudeTie: true,
    aptitude: "SPRINT",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 406,
  },
  {
    name: "Step on the Gas!",
    hasAptitudeTie: true,
    aptitude: "MILE",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 559,
  },
  {
    name: "Technician",
    hasAptitudeTie: true,
    aptitude: "PACE",
    aptitudeScores: {
      tier_SA: 367,
      tier_BC: 301,
      tier_DEF: 267,
      tier_G: 234,
    },
    defaultScore: 367,
  },
  {
    name: "Determined Descent",
    hasAptitudeTie: true,
    aptitude: "PACE",
    aptitudeScores: {
      tier_SA: 367,
      tier_BC: 301,
      tier_DEF: 267,
      tier_G: 234,
    },
    defaultScore: 367,
  },
  {
    name: "Shatterproof",
    hasAptitudeTie: true,
    aptitude: "PACE",
    aptitudeScores: {
      tier_SA: 367,
      tier_BC: 301,
      tier_DEF: 267,
      tier_G: 234,
    },
    defaultScore: 367,
  },
  {
    name: "Hard Worker",
    hasAptitudeTie: true,
    aptitude: "LATE",
    aptitudeScores: {
      tier_SA: 367,
      tier_BC: 301,
      tier_DEF: 267,
      tier_G: 234,
    },
    defaultScore: 367,
  },
  {
    name: "Perfect Prep!",
    hasAptitudeTie: true,
    aptitude: "SPRINT",
    aptitudeScores: {
      tier_SA: 433,
      tier_BC: 355,
      tier_DEF: 315,
      tier_G: 276,
    },
    defaultScore: 315,
  },
  {
    name: "Lightning Step",
    hasAptitudeTie: true,
    aptitude: "MEDIUM",
    aptitudeScores: {
      tier_SA: 433,
      tier_BC: 355,
      tier_DEF: 315,
      tier_G: 276,
    },
    defaultScore: 433,
  },
  {
    name: "Sixth Sense",
    hasAptitudeTie: true,
    aptitude: "FRONT",
    aptitudeScores: {
      tier_SA: 367,
      tier_BC: 301,
      tier_DEF: 267,
      tier_G: 234,
    },
    defaultScore: 267,
  },
  {
    name: "Clairvoyance",
    hasAptitudeTie: true,
    aptitude: "MEDIUM",
    aptitudeScores: {
      tier_SA: 367,
      tier_BC: 301,
      tier_DEF: 267,
      tier_G: 234,
    },
    defaultScore: 367,
  },
  {
    name: "The Bigger Picture",
    hasAptitudeTie: true,
    aptitude: "LATE",
    aptitudeScores: {
      tier_SA: 367,
      tier_BC: 301,
      tier_DEF: 267,
      tier_G: 234,
    },
    defaultScore: 367,
  },
  {
    name: "The Coast Is Clear!",
    hasAptitudeTie: true,
    aptitude: "END",
    aptitudeScores: {
      tier_SA: 367,
      tier_BC: 301,
      tier_DEF: 267,
      tier_G: 234,
    },
    defaultScore: 301,
  },
  {
    name: "Crusader",
    hasAptitudeTie: true,
    aptitude: "END",
    aptitudeScores: {
      tier_SA: 367,
      tier_BC: 301,
      tier_DEF: 267,
      tier_G: 234,
    },
    defaultScore: 301,
  },
  {
    name: "Come What May",
    hasAptitudeTie: true,
    aptitude: "MEDIUM",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 559,
  },
  {
    name: "Headliner",
    hasAptitudeTie: true,
    aptitude: "LONG",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 457,
  },
  {
    name: "Daring Strike",
    hasAptitudeTie: true,
    aptitude: "END",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 457,
  },
  {
    name: "Flash Forward",
    hasAptitudeTie: true,
    aptitude: "MEDIUM",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 559,
  },
  {
    name: "In High Spirits",
    hasAptitudeTie: true,
    aptitude: "SPRINT",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 406,
  },
  {
    name: "Blast Forward",
    hasAptitudeTie: true,
    aptitude: "LONG",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 457,
  },
  {
    name: "Top Runner",
    hasAptitudeTie: true,
    aptitude: "FRONT",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 406,
  },
  {
    name: "Burning Soul",
    hasAptitudeTie: true,
    aptitude: "MEDIUM",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 559,
  },
  {
    name: "Elated",
    hasAptitudeTie: true,
    aptitude: "MEDIUM",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 559,
  },
  {
    name: "Full of Vigor",
    hasAptitudeTie: true,
    aptitude: "MILE",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 559,
  },
  {
    name: "Dauntless",
    hasAptitudeTie: true,
    aptitude: "LATE",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 559,
  },
  {
    name: "Wild Wind",
    hasAptitudeTie: true,
    aptitude: "MEDIUM",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 559,
  },
  {
    name: "Keep Going!",
    hasAptitudeTie: true,
    aptitude: "LATE",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 559,
  },
  {
    name: "Moonlit Flash",
    hasAptitudeTie: true,
    aptitude: "END",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 457,
  },
  {
    name: "Refraction Arc",
    hasAptitudeTie: true,
    aptitude: "MEDIUM",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 559,
  },
  {
    name: "From the Brink",
    hasAptitudeTie: true,
    aptitude: "MEDIUM",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 559,
  },
  {
    name: "Neck and Neck",
    hasAptitudeTie: true,
    aptitude: "PACE",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 559,
  },
  {
    name: "Best in Japan",
    hasAptitudeTie: true,
    aptitude: "LONG",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 457,
  },
  {
    name: "Dominator",
    hasAptitudeTie: true,
    aptitude: "MEDIUM",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 559,
  },
  {
    name: "Petrifying Gaze",
    hasAptitudeTie: true,
    aptitude: "END",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 457,
  },
  {
    name: "Adored by All",
    hasAptitudeTie: true,
    aptitude: "SPRINT",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 406,
  },
  {
    name: "Battle Formation",
    hasAptitudeTie: true,
    aptitude: "MILE",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 559,
  },
  {
    name: "Mystifying Murmur",
    hasAptitudeTie: true,
    aptitude: "MEDIUM",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 559,
  },
  {
    name: "Stamina Siphon",
    hasAptitudeTie: true,
    aptitude: "LONG",
    aptitudeScores: {
      tier_SA: 507,
      tier_BC: 415,
      tier_DEF: 369,
      tier_G: 323,
    },
    defaultScore: 415,
  },
  {
    name: "All-Seeing Eyes",
    hasAptitudeTie: true,
    aptitude: "LATE",
    aptitudeScores: {
      tier_SA: 559,
      tier_BC: 457,
      tier_DEF: 406,
      tier_G: 356,
    },
    defaultScore: 559,
  },
  {
    name: "Illusionist",
    hasAptitudeTie: true,
    aptitude: "LONG",
    aptitudeScores: {
      tier_SA: 367,
      tier_BC: 301,
      tier_DEF: 267,
      tier_G: 234,
    },
    defaultScore: 301,
  },
  {
    name: "Dazzling Disorientation",
    hasAptitudeTie: true,
    aptitude: "PACE",
    aptitudeScores: {
      tier_SA: 367,
      tier_BC: 301,
      tier_DEF: 267,
      tier_G: 234,
    },
    defaultScore: 367,
  },
];
