import { SkillDefinition } from "@/lib/calc/total";

export const YELLOW_SKILLS: SkillDefinition[] = [
  {
    name: "Ignited Spirit SPD",
    hasAptitudeTie: false,
    fixedScore: 263,
  },
  {
    name: "Ignited Spirit PWR",
    hasAptitudeTie: false,
    fixedScore: 263,
  },
  {
    name: "Ignited Spirit GUT",
    hasAptitudeTie: false,
    fixedScore: 263,
  },
  {
    name: "Ignited Spirit WIT",
    hasAptitudeTie: false,
    fixedScore: 263,
  },
  {
    name: "Corner Adept ○",
    hasAptitudeTie: false,
    fixedScore: 217,
  },
  {
    name: "Straightaway Adept",
    hasAptitudeTie: false,
    fixedScore: 217,
  },
  {
    name: "Ramp Up",
    hasAptitudeTie: false,
    fixedScore: 217,
  },
  {
    name: "Homestretch Haste",
    hasAptitudeTie: false,
    fixedScore: 217,
  },
  {
    name: "Uma Stan",
    hasAptitudeTie: false,
    fixedScore: 217,
  },
  {
    name: "Tail Held High",
    hasAptitudeTie: false,
    fixedScore: 217,
  },
  {
    name: "Slipstream",
    hasAptitudeTie: false,
    fixedScore: 217,
  },
  {
    name: "Playtime's Over!",
    hasAptitudeTie: false,
    fixedScore: 217,
  },
  {
    name: "Corner Acceleration ○",
    hasAptitudeTie: false,
    fixedScore: 217,
  },
  {
    name: "Straightaway Acceleration",
    hasAptitudeTie: false,
    fixedScore: 217,
  },
  {
    name: "Nimble Navigator",
    hasAptitudeTie: false,
    fixedScore: 174,
  },
  {
    name: "Highlander",
    hasAptitudeTie: false,
    fixedScore: 217,
  },
  {
    name: "Groundwork",
    hasAptitudeTie: false,
    fixedScore: 217,
  },
  {
    name: "Prudent Positioning",
    hasAptitudeTie: false,
    fixedScore: 129,
  },
  {
    name: "Go with the Flow",
    hasAptitudeTie: false,
    fixedScore: 129,
  },
  {
    name: "Focus",
    hasAptitudeTie: false,
    fixedScore: 129,
  },
  {
    name: "Risky Business",
    hasAptitudeTie: false,
    fixedScore: 129,
  },
  {
    name: "Downhill Speedster",
    hasAptitudeTie: false,
    fixedScore: 217,
  },
  {
    name: "Forward, March!",
    hasAptitudeTie: false,
    fixedScore: 174,
  },
  {
    name: "Glittering Star",
    hasAptitudeTie: false,
    fixedScore: 263,
  },
  {
    name: "Top Pick",
    hasAptitudeTie: false,
    fixedScore: 217,
  },

  // changing base on your aptitude
  {
    name: "Fast-Paced",
    hasAptitudeTie: true,
    aptitude: "FRONT",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 174,
  },
  {
    name: "Prepared to Pass",
    hasAptitudeTie: true,
    aptitude: "PACE",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 239,
  },
  {
    name: "Position Pilfer",
    hasAptitudeTie: true,
    aptitude: "LATE",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 239,
  },
  {
    name: "Outer Swell",
    hasAptitudeTie: true,
    aptitude: "LATE",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 239,
  },
  {
    name: "Masterful Gambit",
    hasAptitudeTie: true,
    aptitude: "END",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 195,
  },
  {
    name: "Gap Closer",
    hasAptitudeTie: true,
    aptitude: "SPRINT",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 174,
  },
  {
    name: "Productive Plan",
    hasAptitudeTie: true,
    aptitude: "MILE",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 239,
  },
  {
    name: "Up-Tempo",
    hasAptitudeTie: true,
    aptitude: "MEDIUM",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 239,
  },
  {
    name: "Steadfast",
    hasAptitudeTie: true,
    aptitude: "MEDIUM",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 239,
  },
  {
    name: "Inside Scoop",
    hasAptitudeTie: true,
    aptitude: "LONG",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 195,
  },
  {
    name: "Sprint Straightaways ◎",
    hasAptitudeTie: true,
    aptitude: "SPRINT",
    aptitudeScores: {
      tier_SA: 288,
      tier_BC: 236,
      tier_DEF: 210,
      tier_G: 183,
    },
    defaultScore: 210,
  },
  {
    name: "Sprint Straightaways ○",
    hasAptitudeTie: true,
    aptitude: "SPRINT",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 174,
  },
  {
    name: "Sprint Corners ◎",
    hasAptitudeTie: true,
    aptitude: "SPRINT",
    aptitudeScores: {
      tier_SA: 288,
      tier_BC: 236,
      tier_DEF: 210,
      tier_G: 183,
    },
    defaultScore: 210,
  },
  {
    name: "Sprint Corners ○",
    hasAptitudeTie: true,
    aptitude: "SPRINT",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 174,
  },
  {
    name: "Huge Lead",
    hasAptitudeTie: true,
    aptitude: "SPRINT",
    aptitudeScores: {
      tier_SA: 288,
      tier_BC: 236,
      tier_DEF: 210,
      tier_G: 183,
    },
    defaultScore: 210,
  },
  {
    name: "Mile Straightaways ◎",
    hasAptitudeTie: true,
    aptitude: "MILE",
    aptitudeScores: {
      tier_SA: 288,
      tier_BC: 236,
      tier_DEF: 210,
      tier_G: 183,
    },
    defaultScore: 288,
  },
  {
    name: "Mile Straightaways ○",
    hasAptitudeTie: true,
    aptitude: "MILE",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 239,
  },
  {
    name: "Mile Corners ◎",
    hasAptitudeTie: true,
    aptitude: "MILE",
    aptitudeScores: {
      tier_SA: 288,
      tier_BC: 236,
      tier_DEF: 210,
      tier_G: 183,
    },
    defaultScore: 288,
  },
  {
    name: "Mile Corners ○",
    hasAptitudeTie: true,
    aptitude: "MILE",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 239,
  },
  {
    name: "Shifting Gears",
    hasAptitudeTie: true,
    aptitude: "MILE",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 239,
  },
  {
    name: "Unyielding Spirit",
    hasAptitudeTie: true,
    aptitude: "MILE",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 239,
  },
  {
    name: "Medium Straightaways ◎",
    hasAptitudeTie: true,
    aptitude: "MEDIUM",
    aptitudeScores: {
      tier_SA: 288,
      tier_BC: 236,
      tier_DEF: 210,
      tier_G: 183,
    },
    defaultScore: 288,
  },
  {
    name: "Medium Straightaways ○",
    hasAptitudeTie: true,
    aptitude: "MEDIUM",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 239,
  },
  {
    name: "Medium Corners ◎",
    hasAptitudeTie: true,
    aptitude: "MEDIUM",
    aptitudeScores: {
      tier_SA: 288,
      tier_BC: 236,
      tier_DEF: 210,
      tier_G: 183,
    },
    defaultScore: 288,
  },
  {
    name: "Medium Corners ○",
    hasAptitudeTie: true,
    aptitude: "MEDIUM",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 239,
  },
  {
    name: "Long Straightaways ◎",
    hasAptitudeTie: true,
    aptitude: "LONG",
    aptitudeScores: {
      tier_SA: 288,
      tier_BC: 236,
      tier_DEF: 210,
      tier_G: 183,
    },
    defaultScore: 236,
  },
  {
    name: "Long Straightaways ○",
    hasAptitudeTie: true,
    aptitude: "LONG",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 195,
  },
  {
    name: "Long Corners ◎",
    hasAptitudeTie: true,
    aptitude: "LONG",
    aptitudeScores: {
      tier_SA: 288,
      tier_BC: 236,
      tier_DEF: 210,
      tier_G: 183,
    },
    defaultScore: 236,
  },
  {
    name: "Long Corners ○",
    hasAptitudeTie: true,
    aptitude: "LONG",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 195,
  },
  {
    name: "Keeping the Lead",
    hasAptitudeTie: true,
    aptitude: "LONG",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 195,
  },
  {
    name: "Pressure",
    hasAptitudeTie: true,
    aptitude: "LONG",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 195,
  },
  {
    name: "Front Runner Straightaways ◎",
    hasAptitudeTie: true,
    aptitude: "FRONT",
    aptitudeScores: {
      tier_SA: 288,
      tier_BC: 236,
      tier_DEF: 210,
      tier_G: 183,
    },
    defaultScore: 210,
  },
  {
    name: "Front Runner Straightaways ○",
    hasAptitudeTie: true,
    aptitude: "FRONT",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 174,
  },
  {
    name: "Front Runner Corners ◎",
    hasAptitudeTie: true,
    aptitude: "FRONT",
    aptitudeScores: {
      tier_SA: 288,
      tier_BC: 236,
      tier_DEF: 210,
      tier_G: 183,
    },
    defaultScore: 210,
  },
  {
    name: "Front Runner Corners ○",
    hasAptitudeTie: true,
    aptitude: "FRONT",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 174,
  },
  {
    name: "Leader's Pride",
    hasAptitudeTie: true,
    aptitude: "FRONT",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 174,
  },
  {
    name: "Pace Chaser Straightaways ◎",
    hasAptitudeTie: true,
    aptitude: "PACE",
    aptitudeScores: {
      tier_SA: 288,
      tier_BC: 236,
      tier_DEF: 210,
      tier_G: 183,
    },
    defaultScore: 288,
  },
  {
    name: "Pace Chaser Straightaways ○",
    hasAptitudeTie: true,
    aptitude: "PACE",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 239,
  },
  {
    name: "Pace Chaser Corners ◎",
    hasAptitudeTie: true,
    aptitude: "PACE",
    aptitudeScores: {
      tier_SA: 288,
      tier_BC: 236,
      tier_DEF: 210,
      tier_G: 183,
    },
    defaultScore: 288,
  },
  {
    name: "Pace Chaser Corners ○",
    hasAptitudeTie: true,
    aptitude: "PACE",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 239,
  },
  {
    name: "Late Surger Straightaways ◎",
    hasAptitudeTie: true,
    aptitude: "LATE",
    aptitudeScores: {
      tier_SA: 288,
      tier_BC: 236,
      tier_DEF: 210,
      tier_G: 183,
    },
    defaultScore: 288,
  },
  {
    name: "Late Surger Straightaways ○",
    hasAptitudeTie: true,
    aptitude: "LATE",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 239,
  },
  {
    name: "Later Surger Corners ◎",
    hasAptitudeTie: true,
    aptitude: "LATE",
    aptitudeScores: {
      tier_SA: 288,
      tier_BC: 236,
      tier_DEF: 210,
      tier_G: 183,
    },
    defaultScore: 288,
  },
  {
    name: "Late Surger Corners ○",
    hasAptitudeTie: true,
    aptitude: "LATE",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 239,
  },
  {
    name: "1,500,000 CC",
    hasAptitudeTie: true,
    aptitude: "LATE",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 239,
  },
  {
    name: "End Closer Straightaways ◎",
    hasAptitudeTie: true,
    aptitude: "END",
    aptitudeScores: {
      tier_SA: 288,
      tier_BC: 236,
      tier_DEF: 210,
      tier_G: 183,
    },
    defaultScore: 236,
  },
  {
    name: "End Closer Straightaways ○",
    hasAptitudeTie: true,
    aptitude: "END",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 195,
  },
  {
    name: "End Closer Corners ◎",
    hasAptitudeTie: true,
    aptitude: "END",
    aptitudeScores: {
      tier_SA: 288,
      tier_BC: 236,
      tier_DEF: 210,
      tier_G: 183,
    },
    defaultScore: 236,
  },
  {
    name: "End Closer Corners ○",
    hasAptitudeTie: true,
    aptitude: "END",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 195,
  },

  {
    name: "Early Lead",
    hasAptitudeTie: true,
    aptitude: "FRONT",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 174,
  },
  {
    name: "Final Push",
    hasAptitudeTie: true,
    aptitude: "FRONT",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 174,
  },
  {
    name: "Head-On",
    hasAptitudeTie: true,
    aptitude: "PACE",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 239,
  },
  {
    name: "Slick Surge",
    hasAptitudeTie: true,
    aptitude: "LATE",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 239,
  },
  {
    name: "Straightaway Spurt",
    hasAptitudeTie: true,
    aptitude: "END",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 195,
  },
  {
    name: "Sprinting Gear",
    hasAptitudeTie: true,
    aptitude: "SPRINT",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 174,
  },
  {
    name: "Updrafters",
    hasAptitudeTie: true,
    aptitude: "MILE",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 239,
  },
  {
    name: "Countermeasure",
    hasAptitudeTie: true,
    aptitude: "SPRINT",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 174,
  },
  {
    name: "Acceleration",
    hasAptitudeTie: true,
    aptitude: "MILE",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 239,
  },
  {
    name: "Second Wind",
    hasAptitudeTie: true,
    aptitude: "FRONT",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 174,
  },
  {
    name: "Shrewd Step",
    hasAptitudeTie: true,
    aptitude: "PACE",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 239,
  },
  {
    name: "Straight Descent",
    hasAptitudeTie: true,
    aptitude: "PACE",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 239,
  },
  {
    name: "Tactical Tweak",
    hasAptitudeTie: true,
    aptitude: "PACE",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 239,
  },
  {
    name: "Fighter",
    hasAptitudeTie: true,
    aptitude: "LATE",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 239,
  },
  {
    name: "Meticulous Measures",
    hasAptitudeTie: true,
    aptitude: "LATE",
    aptitudeScores: {
      tier_SA: 191,
      tier_BC: 157,
      tier_DEF: 139,
      tier_G: 122,
    },
    defaultScore: 139,
  },
  {
    name: "Thunderbolt Step",
    hasAptitudeTie: true,
    aptitude: "MEDIUM",
    aptitudeScores: {
      tier_SA: 191,
      tier_BC: 157,
      tier_DEF: 139,
      tier_G: 122,
    },
    defaultScore: 191,
  },
  {
    name: "Dodging Danger",
    hasAptitudeTie: true,
    aptitude: "FRONT",
    aptitudeScores: {
      tier_SA: 143,
      tier_BC: 116,
      tier_DEF: 103,
      tier_G: 90,
    },
    defaultScore: 103,
  },
  {
    name: "Hawkeye",
    hasAptitudeTie: true,
    aptitude: "MEDIUM",
    aptitudeScores: {
      tier_SA: 142,
      tier_BC: 116,
      tier_DEF: 103,
      tier_G: 90,
    },
    defaultScore: 142,
  },
  {
    name: "Studious",
    hasAptitudeTie: true,
    aptitude: "LATE",
    aptitudeScores: {
      tier_SA: 94,
      tier_BC: 77,
      tier_DEF: 68,
      tier_G: 60,
    },
    defaultScore: 94,
  },
  {
    name: "I Can See Right Through You",
    hasAptitudeTie: true,
    aptitude: "END",
    aptitudeScores: {
      tier_SA: 94,
      tier_BC: 77,
      tier_DEF: 68,
      tier_G: 60,
    },
    defaultScore: 77,
  },
  {
    name: "Strategist",
    hasAptitudeTie: true,
    aptitude: "END",
    aptitudeScores: {
      tier_SA: 94,
      tier_BC: 77,
      tier_DEF: 68,
      tier_G: 60,
    },
    defaultScore: 77,
  },
  {
    name: "All I've Got",
    hasAptitudeTie: true,
    aptitude: "MEDIUM",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 239,
  },
  {
    name: "Feature Act",
    hasAptitudeTie: true,
    aptitude: "LONG",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 195,
  },
  {
    name: "Early Start",
    hasAptitudeTie: true,
    aptitude: "END",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 195,
  },
  {
    name: "Light as a Feather",
    hasAptitudeTie: true,
    aptitude: "SPRINT",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 174,
  },
  {
    name: "Fighting Spirit",
    hasAptitudeTie: true,
    aptitude: "MEDIUM",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 239,
  },
  {
    name: "Eager",
    hasAptitudeTie: true,
    aptitude: "MEDIUM",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 239,
  },
  {
    name: "Pumped",
    hasAptitudeTie: true,
    aptitude: "MILE",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 239,
  },
  {
    name: "Fearless",
    hasAptitudeTie: true,
    aptitude: "LATE",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 239,
  },
  {
    name: "With All My Soul",
    hasAptitudeTie: true,
    aptitude: "MEDIUM",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 239,
  },
  {
    name: "Full Throttle",
    hasAptitudeTie: true,
    aptitude: "LATE",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 239,
  },
  {
    name: "Take the Chance",
    hasAptitudeTie: true,
    aptitude: "MEDIUM",
    aptitudeScores: {
      tier_SA: 239,
      tier_BC: 195,
      tier_DEF: 174,
      tier_G: 152,
    },
    defaultScore: 239,
  },
];
